### ISSUE TITLE
Does Not Work on windows

### ISSUE THREAD

**Issue by harshit2608** [optimizacija/neovim-config#2]
###  Installation Failed on Windows

**OS : Windows 10**
**NeoVim Version : NVIM v0.5.0 released  on Jul 2**

I cloned the repo and placed at the path:
C:\Users\<User Name>\AppData\Local\nvim

When i ran the command ```:PackerInstall``` it gave me an error saying
`E492: Not an editor command: PackerInstall`

![Screenshot 2021-08-19 013308](https://user-images.githubusercontent.com/42277796/129964529-c6f1371a-01d7-4e58-a921-ffdaf512be21.png)

**Comment by optimizacija** [comment]
Hey, I haven't really tried it on Windows, but it looks like you need to install packer first. Follow this guide https://github.com/wbthomason/packer.nvim

I wrote it in the short installation guide in the readme: https://github.com/optimizacija/neovim-config#installation

**Comment by elkrien** [comment]
The same issue is on Linux. When You run nvim for the first time after config installation there are errors and plugins.lua is not executed. To correct it You need to modify init.lua and move line `require ('plugins')` to the top - as the first line. Then just start nvim and execute :PackerInstall. Close nvim and run again and all should work correctly.

**Comment by harshit2608** [comment]
> The same issue is on Linux. When You run nvim for the first time after config installation there are errors and plugins.lua is not executed. To correct it You need to modify init.lua and move line `require ('plugins')` to the top - as the first line. Then just start nvim and execute :PackerInstall. Close nvim and run again and all should work correctly. 

This method solved the issue thanks 👍🏻

**Comment by HypsterOP** [comment]
> The same issue is on Linux. When You run nvim for the first time after config installation there are errors and plugins.lua is not executed. To correct it You need to modify init.lua and move line `require ('plugins')` to the top - as the first line. Then just start nvim and execute :PackerInstall. Close nvim and run again and all should work correctly.

Yes this works! use this method if you are facing this error!

**Comment by optimizacija** [comment]
Thank you @elkrien for taking the time to solve this issue. I haven't had a chance to work on my personal projects lately.
So, I'll come back around to it when I can and do some fixer uppers over the whole config. 
Note that, I saw the proposed fix here from @HypsterOP: https://github.com/optimizacija/neovim-config/pull/4 
I'll give it a go when I have more free time on my hands

**Comment by optimizacija** [comment]
I fixed the errors that were appearing on fresh installs. I tested it on a Linux machine, but in _theory_ it should work on Windows machine as well. Check out the updated [README.md](https://github.com/optimizacija/neovim-config/blob/master/README.md) for new installation process.
