### ISSUE TITLE
Nvim gives error when run

### ISSUE THREAD

**Issue by victoriyus** [optimizacija/neovim-config#8]
I get the following error when I try to run neovim:

`Error detected while processing /home/a/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/a/.config/nvim/lua/plugins.lua:
2: attempt to concatenate global 'DATA_PATH' (a nil value)
stack traceback:
        /home/a/.config/nvim/lua/plugins.lua:2: in main chunk
        [C]: in function 'require'
        /home/a/.config/nvim/init.lua:1: in main chunk
Press ENTER or type command to continue`

**Comment by optimizacija** [comment]
@victoriyus apologies for the late reply. I updated the config to work with updated dependencies. It might resolve your issue.  Please let me know if it helped.

**Comment by victoriyus** [comment]
Sorry for the limited info in my original comment, but this indeed fixed my issue, thanks!
